### ISSUE TITLE
TODO model init

### ISSUE THREAD

**Issue by phrase5036** [5fpro/jupiter#63]
Table - todos, 是存放預計要做的工作事項
- [x] user_id, project_id, date, desc(text), record_ids(serlize)
- [x] 必填 : [user_id, project_id], 其餘在context驗證

Table records
- [x] 新增欄位 todo_id (bind時紀錄)
